-- Trouble: Pretty diagnostics and quickfix with beautiful UI
return {
  "folke/trouble.nvim",
  dependencies = { "nvim-tree/nvim-web-devicons" },
  cmd = { "Trouble" },
  keys = {
    { "<leader>xx", "<cmd>Trouble diagnostics toggle<cr>", desc = "Diagnostics" },
    { "<leader>xX", "<cmd>Trouble diagnostics toggle filter.buf=0<cr>", desc = "Buffer Diagnostics" },
    { "<leader>xq", "<cmd>Trouble qflist toggle<cr>", desc = "Quickfix" },
    { "<leader>xl", "<cmd>Trouble loclist toggle<cr>", desc = "Location List" },
    { "<leader>xs", "<cmd>Trouble symbols toggle focus=false<cr>", desc = "Symbols" },
    { "<leader>xr", "<cmd>Trouble lsp_references toggle<cr>", desc = "LSP References" },
  },
  opts = {
    auto_close = true,
    auto_preview = true,
    focus = true,
    follow = true,
    indent_guides = true,
    multiline = true,
    win = {
      type = "split",
      position = "bottom",
      size = 10,
    },
    preview = {
      type = "main",
      scratch = true,
    },
    icons = {
      indent = {
        top           = "│ ",
        middle        = "├╴",
        last          = "╰╴",
        fold_open     = " ",
        fold_closed   = " ",
        ws            = "  ",
      },
      folder_closed = " ",
      folder_open   = " ",
      kinds = {
        Array         = " ",
        Boolean       = "󰨙 ",
        Class         = " ",
        Constant      = "󰏿 ",
        Constructor   = " ",
        Enum          = " ",
        EnumMember    = " ",
        Event         = " ",
        Field         = " ",
        File          = " ",
        Function      = "󰊕 ",
        Interface     = " ",
        Key           = " ",
        Method        = "󰊕 ",
        Module        = " ",
        Namespace     = "󰦮 ",
        Null          = " ",
        Number        = "󰎠 ",
        Object        = " ",
        Operator      = " ",
        Package       = " ",
        Property      = " ",
        String        = " ",
        Struct        = "󰆼 ",
        TypeParameter = " ",
        Variable      = "󰀫 ",
      },
    },
  },
}
